// deliver-ebook.js ~ Secure ebook delivery for vibrationofawesome.com
//
// GET ?token=XXXXX&product=free|paid
// Validates token against VALID_EBOOK_TOKENS (comma-separated env var).
// Redirects to the ebook PDF at its unguessable static path.
//
// Env vars required:
//   VALID_EBOOK_TOKENS   ~ comma-separated list of valid one-time tokens
//   FREE_EBOOK_PATH      ~ e.g. /dl/a7f3k9x2m4p8q1w6/field-guide.pdf
//   PAID_EBOOK_PATH      ~ e.g. /dl/b2n8h5r7t3y6u1i4/user-manual.pdf
//   SITE_URL             ~ e.g. https://vibrationofawesome.com
//
// Token lifecycle:
//   Tokens are generated by capture-email.js at signup time.
//   This function validates but does NOT revoke tokens (stateless for now).
//   To add single-use enforcement: move VALID_EBOOK_TOKENS to a KV store or DB.

"use strict";

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "Content-Type",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
};

exports.handler = async function (event) {
  if (event.httpMethod === "OPTIONS") {
    return { statusCode: 204, headers: CORS, body: "" };
  }

  const params  = event.queryStringParameters || {};
  const token   = (params.token || "").trim();
  const product = (params.product || "free").toLowerCase();

  if (!token) {
    return {
      statusCode: 400,
      headers: { ...CORS, "Content-Type": "text/html" },
      body: "<p>Missing download token. Please use the link from your confirmation email.</p>",
    };
  }

  // Validate token
  const validTokens = (process.env.VALID_EBOOK_TOKENS || "")
    .split(",")
    .map(t => t.trim())
    .filter(Boolean);

  if (!validTokens.includes(token)) {
    return {
      statusCode: 403,
      headers: { ...CORS, "Content-Type": "text/html" },
      body: "<p>Invalid or expired download token. Please sign up again at <a href=\"/field-guide/\">vibrationofawesome.com/field-guide/</a></p>",
    };
  }

  // Determine which ebook to serve
  const siteUrl  = (process.env.SITE_URL || "https://vibrationofawesome.com").replace(/\/$/, "");
  const freePath = process.env.FREE_EBOOK_PATH || "/dl/a7f3k9x2m4p8q1w6/field-guide.pdf";
  const paidPath = process.env.PAID_EBOOK_PATH || "/dl/b2n8h5r7t3y6u1i4/user-manual.pdf";

  const filePath = product === "paid" ? paidPath : freePath;
  const redirectUrl = `${siteUrl}${filePath}`;

  return {
    statusCode: 302,
    headers: {
      ...CORS,
      Location: redirectUrl,
      "Cache-Control": "no-store",
    },
    body: "",
  };
};
