baseURL = "https://vibrationofawesome.com/"
languageCode = "en-us"
title = "Vibration of Awesome"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Empower Thyself. Empower the Earth. A philosophy for building a life that is actually yours."
  author = "Matty BOOMBOOM"

[permalinks]
  posts = "/posts/:slug/"
