backend:
  name: github
  repo: Lordshrrred/VibrationofAwesome
  branch: main
  site_domain: vibrationofawesome.netlify.app

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Canonical URL (if cross-posted)", name: "canonical", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "content/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Vibration of Awesome"
        name: "vibration"
        file: "content/vibration.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
